# Exploration

In [2]:
import robosuite as suite
import numpy as np

import torch 
import torch.nn as nn

In [3]:
env = suite.make(
    env_name="Lift",
    robots="Panda",
    has_renderer=False,
    has_offscreen_renderer=False,
    use_camera_obs=False,
    use_object_obs=True,                    
    horizon = 200, 
    reward_shaping=True                 
)

In [6]:
# reset the environment
env.reset()

for i in range(200):
    action = np.random.randn(env.robots[0].dof) # sample random action
    obs, reward, done, info = env.step(action)  # take action in the environment
    print(reward)

Creating window glfw
0.0076426213294075295
0.006922424974866084
0.00629704770881265
0.005438453344064786
0.004321243849638772
0.003287782379950372
0.002565531283279644
0.0020979434199757856
0.0017984217468564661
0.0016282572479821133
0.0015123674424828671
0.0014156043365783787
0.0013233869384866716
0.0012684380493387258
0.0013083112111017413
0.0014019194674896873
0.0015528130039148792
0.0018013423425640655
0.0022624464353404347
0.002976071594332355
0.0039924455302851785
0.0057581826186757406
0.008279459954083091
0.01060635497571284
0.01114559675527671
0.010008697449792504
0.008577621541466079
0.006741492599918815
0.0047679312549423845
0.003554203269922309
0.002613210734664781
0.0018947510206114909
0.0015196487750965579
0.0012098054388367035
0.001041379387578583
0.0009996624795629572
0.0009443601715953696
0.0008565976806662847
0.0007746617990339722
0.0006987603907273845
0.0006054858382309211
0.00047352718061599575
0.000379501728776383
0.0003185233201560401
0.0002729354043129955
0.000267

In [21]:
env.observation_spec()

OrderedDict([('robot0_joint_pos',
              array([ 0.10172172,  0.35560393, -0.05976065, -2.58338028,  0.0077407 ,
                      3.75514215,  0.71860747])),
             ('robot0_joint_vel',
              array([ 0.42129338,  0.03059858, -0.5162297 , -0.25807786,  0.2971956 ,
                     -0.03155466, -0.47641039])),
             ('robot0_eef_pos',
              array([-0.00606036,  0.02063334,  1.07927953])),
             ('robot0_eef_quat',
              array([0.91611114, 0.05198596, 0.39728684, 0.01417765])),
             ('robot0_gripper_qpos', array([ 0.03030115, -0.02998849])),
             ('robot0_gripper_qvel', array([ 0.18707932, -0.10815132])),
             ('robot0_robot-state',
              array([ 0.10154639,  0.34815657, -0.05972508, -0.52967078,  0.00774062,
                     -0.57577318,  0.65833712,  0.9948308 ,  0.9374364 ,  0.99821486,
                     -0.84820332,  0.99997004, -0.81760947,  0.75272321,  0.42129338,
                    

# REINFORCE Model Debug

In [51]:
class ReinforceModel(nn.Module):
    def __init__(self, env):
        super(ReinforceModel, self).__init__()
        self.state_dim =  env # Need to update: robot and object states
        self.action_dim = env.action_dim
        
        self.l1 = nn.Linear(self.state_space, 128, bias = False)
        self.l2 = nn.Linear(128, self.action_dim, bias = False)
        
        self.gamma = gamma
        
        # Episode policy and reward history 
        self.policy_history = Variable(torch.Tensor()) 
        self.reward_episode = []
        # Overall reward and loss history
        self.reward_history = []
        self.loss_history = []
        
    def forward(self,x):
        model = nn.Sequential(
            self.l1,
            nn.Dropout(p=0.6),
            nn.ReLU(),
            self.l2,
            nn.Softmax(dim=-1)
         )
        return model(x)
    
    def select_action():
        

# PPO Model Debug

# DDPG Model Debug